### ISSUE TITLE
Import refextract fails 

### ISSUE THREAD

**Issue by Omar-Aboelsoud** [inspirehep/refextract#57]
I am trying to import refextract using python 2 and python 3 both fails . It shows the error below .
![image](https://user-images.githubusercontent.com/6435445/38551783-5fea346e-3cba-11e8-8716-6301c3fc35ba.png)
I installed it using **pip install refextract** as mentioned in readme file

**Comment by Omar-Aboelsoud** [comment]
@openp2pdesign  I am using windows , I installed it using Anaconda with pip install command , but It fail when I import it

**Comment by Nihabr** [comment]
Im having a similar issue when importing refextract, however mine does not appear to be libmagic related:
![refextract error](https://user-images.githubusercontent.com/8914860/43714195-81c1dd02-997c-11e8-925c-871cb94dd72b.png)

Im using python 3.6.5 on Windows 10, and refextract was installed using pip.

The import code is the same as in the project description example: `from refextract import extract_references_from_file`

**Comment by bastiankayser** [comment]
Same here, Python 3.6.3 on Windows 10, refextract was installed using pip.
`from refextract import extract_references_from_file`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\BKY\AppData\Roaming\Python\Python36\site-packages\refextract\__init__.py", line 28, in <module>
    from .references.api import (
  File "C:\Users\BKY\AppData\Roaming\Python\Python36\site-packages\refextract\references\api.py", line 96
    raise FullTextNotAvailableError(u"URL not found: '{0}'".format(url)), None, sys.exc_info()[2]
                                                                        ^
SyntaxError: invalid syntax

**Comment by pradhanphy** [comment]
This also happens in Linux(Debian). Install it using pip3. 

Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from refextract import extract_references_from_file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/refextract/__init__.py", line 28, in <module>
    from .references.api import (
  File "/usr/local/lib/python3.5/dist-packages/refextract/references/api.py", line 96
    raise FullTextNotAvailableError(u"URL not found: '{0}'".format(url)), None, sys.exc_info()[2]
                                                                        ^
SyntaxError: invalid syntax
>>> exit()

**Comment by RaymondCui21** [comment]
Same here, Python 2.7 on Windows 7, refextract was installed using pip. 
Errors from Pycharm:
  File "C:\~\venv\2.7\lib\site-packages\magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by RaymondCui21** [comment]
Could the developers provide more workable environment details to repeat the processes, such as  OS, Python versions, IDE? Many thanks.

**Comment by pHequals7** [comment]
Is the project even maintained? Have the same importing error throws out invalid syntax error. Please solve it ASAP

**Comment by patel-zeel** [comment]
This works for me on python 3.6 on colab.

sudo apt-get install -y python-magic

**Comment by michamos** [comment]
The previous version was not compatible with Python 3. Version 1.* is Python 3 only.

**Comment by AxelBerres** [comment]
you need to install the related magic bin package

**Comment by kingsj0405** [comment]
I'm failing without any exception...

```shell script
>python
Python 3.8.2 (default, May  6 2020, 09:02:42) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from refextract import extract_references_from_url
# Just die without logging
>
```

**Comment by walter-hernandez** [comment]
For anyone experiencing this issue, this happens because you need to have [magic-bin](https://pypi.org/project/python-magic-bin/) installed. Then, the solution is:

`pip install python-magic-bin`

**Comment by shreyashgupta68** [comment]
I have already installed the magic bin still getting the same error.

**Comment by josePereiro** [comment]
> 

This just worked for me `Python 3.8.5` `refextract 1.1.4`
